openapi: 3.0.2
info:
    title: Barbershop-API
    version: 1.0.0
    description: '### This is a Swagger UI for our games API'
paths:
    '/barbers/{id}':
        get:
            tags:
                - details
            parameters:
                -
                    examples:
                        Id:
                            value:
                                id: 1
                    name: id
                    description: Barber id
                    schema:
                        type: array
                        items:
                            type: string
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                Full details of a given barber:
                                    value: '{"id":1, "name":"Kaire","Contact_Details":"Kaire@gmail.com"'
                    description: |
                        Returns full details of a given id barber
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                Barber /w+ was not found:
                                    value: Game\\w+ was not found in barber array
                    description: Barber was not in barbers array
            operationId: Barber id
            summary: Get full details of barber
            description: |
                Returns full details of a given id barber
        delete:
            requestBody:
                description: Delete-barber
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/delete-barber'
                required: true
            tags:
                - Delete
            responses:
                '204':
                    description: Deleted barber
                '404':
                    content:
                        application/json:
                            schema:
                                type: string
                    description: Barber was not deleted
            summary: Delete full details of barber
            description: |
                Deletes full details of a given id barber
    /barbers:
        get:
            tags:
                - barbers
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                List of barbers:
                                    value:
                                        - Maire
                                        - Kalle
                    description: |
                        Returns a list of barbers
            summary: Get a list of all barbers
            description: Returns a list of all barbers in API
        post:
            requestBody:
                description: A new barber to be created
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/new-barber'
                        examples:
                            example:
                                value:
                                    contact_details: 86.76
                                    name: Juuri
                required: true
            tags:
                - barbers
            responses:
                '201':
                    description: New barber has been created
                '400':
                    description: One or all params are missing
            deprecated: false
            summary: creates a barber
            description: |
                Post a new barber
    /services:
        get:
            tags:
                - services
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                List of services:
                                    value: |-
                                        [
                                            "Men cut"
                                            "Women cut"
                                            "Hair coloring"

                                            
                                        ]
                    description: Returns a list of all services in API
            summary: Get a list of all Services
            description: Returns a list of all services in API
    '/services/{id}':
        get:
            tags:
                - details
            parameters:
                -
                    examples:
                        Service id:
                            value:
                                id: 1
                    name: id
                    description: Service id
                    schema:
                        type: array
                        items:
                            type: string
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: string
                            examples:
                                Full details of given services:
                                    value:
                                        id: 1
                                        Service_name: Meestelõikus
                                        Price: 5$
                                        Description: Masinlõikus
                    description: |
                        Returns full details of a given id service
                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error'
                            examples:
                                error:
                                    value:
                                        error: Error message.
                    description: Service was not found in service array
            operationId: Service id
            summary: Get full details of service
            description: |
                Returns full details of a given id service
        parameters:
            -
                name: id
                in: path
                required: true
components:
    schemas:
        error:
            title: Root Type for error
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        delete-barber:
            description: ''
            required:
                - id
            type: object
            properties:
                id:
                    description: ''
                    type: string
            example:
                id: 1
        new-barber:
            description: ''
            type: object
            properties:
                contact_details:
                    format: float
                    description: ''
                    type: number
                name:
                    description: ''
                    type: string
